### ISSUE TITLE
Tasks allow empty titles

### ISSUE THREAD

**Issue by haacked** [Haacked/todo-app#13]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

_Sentiment Bot Says: Hey now, let's keep it positive._

**Comment by Haacked** [comment]
Making a test comment

**Comment by Haacked** [comment]
Another comment made by me.

**Comment by Haacked** [comment]
Yet another comment.

**Comment by Haacked** [comment]
Ha ha ha

**Comment by Haacked** [comment]
aotehusanoethuaosntehu

**Comment by Haacked** [comment]
Just another day in paradise

**Comment by Haacked** [comment]
One banana. One banana. One banana.

**Comment by Haacked** [comment]
Chimichangas are flaky and delicious.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you. Terrible.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

**Comment by Haacked** [comment]
This is crap. You suck. I hate you.

**Comment by haacked** [comment]
I'm just testing here, but this really sucks. You're terrible. You really are bad. Boo on you.

_Sentiment Bot Says: Hey now, let's keep it positive._
